# Generated by Django 5.0.6 on 2024-07-09 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0004_userprofile_email_userprofile_firstname_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='logintable',
            name='email',
            field=models.EmailField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='logintable',
            name='firstname',
            field=models.CharField(default=1234, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='logintable',
            name='lastname',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
